package microservice.online.entity;
// Generated 2017-4-19 16:46:12 by Hibernate Tools 3.2.2.GA

/**
 * TbRole generated by hbm2java
 */
public class TbRole implements java.io.Serializable {

	private int id;
	private String name;
	private String introduce;
	private String state;

	public TbRole() {
	}

	public TbRole(int id) {
		this.id = id;
	}

	public TbRole(int id, String name, String introduce, String state) {
		this.id = id;
		this.name = name;
		this.introduce = introduce;
		this.state = state;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getIntroduce() {
		return this.introduce;
	}

	public void setIntroduce(String introduce) {
		this.introduce = introduce;
	}

	public String getState() {
		return this.state;
	}

	public void setState(String state) {
		this.state = state;
	}

}
