package microservice.online.entity;
// Generated 2017-4-19 16:46:12 by Hibernate Tools 3.2.2.GA

/**
 * TbRoleSecqurity generated by hbm2java
 */
public class TbRoleSecqurity implements java.io.Serializable {

	private TbRoleSecqurityId id;

	public TbRoleSecqurity() {
	}

	public TbRoleSecqurity(TbRoleSecqurityId id) {
		this.id = id;
	}

	public TbRoleSecqurityId getId() {
		return this.id;
	}

	public void setId(TbRoleSecqurityId id) {
		this.id = id;
	}

}
