package microservice.online.entity;
// Generated 2017-4-19 16:46:12 by Hibernate Tools 3.2.2.GA

/**
 * TbSecqurity generated by hbm2java
 */
public class TbSecqurity implements java.io.Serializable {

	private int id;
	private String action;
	private String des;
	private String menuName;
	private Integer pid;
	private String ismenu;
	private String icon;

	public TbSecqurity() {
	}

	public TbSecqurity(int id) {
		this.id = id;
	}

	public TbSecqurity(int id, String action, String des, String menuName, Integer pid, String ismenu, String icon) {
		this.id = id;
		this.action = action;
		this.des = des;
		this.menuName = menuName;
		this.pid = pid;
		this.ismenu = ismenu;
		this.icon = icon;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public String getAction() {
		return this.action;
	}

	public void setAction(String action) {
		this.action = action;
	}

	public String getDes() {
		return this.des;
	}

	public void setDes(String des) {
		this.des = des;
	}

	public String getMenuName() {
		return this.menuName;
	}

	public void setMenuName(String menuName) {
		this.menuName = menuName;
	}

	public Integer getPid() {
		return this.pid;
	}

	public void setPid(Integer pid) {
		this.pid = pid;
	}

	public String getIsmenu() {
		return this.ismenu;
	}

	public void setIsmenu(String ismenu) {
		this.ismenu = ismenu;
	}

	public String getIcon() {
		return this.icon;
	}

	public void setIcon(String icon) {
		this.icon = icon;
	}

}
