package microservice.online.entity;
// Generated 2017-4-19 16:46:12 by Hibernate Tools 3.2.2.GA

/**
 * TbUserRole generated by hbm2java
 */
public class TbUserRole implements java.io.Serializable {

	private TbUserRoleId id;

	public TbUserRole() {
	}

	public TbUserRole(TbUserRoleId id) {
		this.id = id;
	}

	public TbUserRoleId getId() {
		return this.id;
	}

	public void setId(TbUserRoleId id) {
		this.id = id;
	}

}
