package microservice.online.entity;
// Generated 2017-4-19 16:46:12 by Hibernate Tools 3.2.2.GA

import java.util.Date;

/**
 * TbUser generated by hbm2java
 */
public class TbUser implements java.io.Serializable {

	private int cid;
	private String username;
	private String password;
	private String nickname;
	private Integer headimgid;
	private Date rgtime;
	private Integer infoid;
	private String state;

	public TbUser() {
	}

	public TbUser(int cid) {
		this.cid = cid;
	}

	public TbUser(int cid, String username, String password, String nickname, Integer headimgid, Date rgtime,
			Integer infoid, String state) {
		this.cid = cid;
		this.username = username;
		this.password = password;
		this.nickname = nickname;
		this.headimgid = headimgid;
		this.rgtime = rgtime;
		this.infoid = infoid;
		this.state = state;
	}

	public int getCid() {
		return this.cid;
	}

	public void setCid(int cid) {
		this.cid = cid;
	}

	public String getUsername() {
		return this.username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	public String getNickname() {
		return this.nickname;
	}

	public void setNickname(String nickname) {
		this.nickname = nickname;
	}

	public Integer getHeadimgid() {
		return this.headimgid;
	}

	public void setHeadimgid(Integer headimgid) {
		this.headimgid = headimgid;
	}

	public Date getRgtime() {
		return this.rgtime;
	}

	public void setRgtime(Date rgtime) {
		this.rgtime = rgtime;
	}

	public Integer getInfoid() {
		return this.infoid;
	}

	public void setInfoid(Integer infoid) {
		this.infoid = infoid;
	}

	public String getState() {
		return this.state;
	}

	public void setState(String state) {
		this.state = state;
	}

}
