package microservice.online.entity;
// Generated 2017-4-19 18:24:38 by Hibernate Tools 3.2.2.GA

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * TbAdminUser generated by hbm2java
 */
@Entity
@Table(name = "tb_admin_user", catalog = "wx_manage")
public class TbAdminUser implements java.io.Serializable {

	private static final long serialVersionUID = 8998595495421484663L;
	private int id;
	private String username;
	private String password;
	private String phone;
	private String email;
	private String crtime;
	private String state;

	public TbAdminUser() {
	}

	public TbAdminUser(int id) {
		this.id = id;
	}

	public TbAdminUser(int id, String username, String password, String phone, String email, String crtime,
			String state) {
		this.id = id;
		this.username = username;
		this.password = password;
		this.phone = phone;
		this.email = email;
		this.crtime = crtime;
		this.state = state;
	}

	@Id

	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "username", length = 20)
	public String getUsername() {
		return this.username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	@Column(name = "password", length = 20)
	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	@Column(name = "phone", length = 15)
	public String getPhone() {
		return this.phone;
	}

	public void setPhone(String phone) {
		this.phone = phone;
	}

	@Column(name = "email", length = 50)
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@Column(name = "crtime", length = 50)
	public String getCrtime() {
		return this.crtime;
	}

	public void setCrtime(String crtime) {
		this.crtime = crtime;
	}

	@Column(name = "state", length = 5)
	public String getState() {
		return this.state;
	}

	public void setState(String state) {
		this.state = state;
	}

}
