package microservice.online.entity;
// Generated 2017-4-19 18:24:38 by Hibernate Tools 3.2.2.GA

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * TbRoleSecqurity generated by hbm2java
 */
@Entity
@Table(name = "tb_role_secqurity", catalog = "wx_manage")
public class TbRoleSecqurity implements java.io.Serializable {

	private TbRoleSecqurityId id;

	public TbRoleSecqurity() {
	}

	public TbRoleSecqurity(TbRoleSecqurityId id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({ @AttributeOverride(name = "rid", column = @Column(name = "rid", nullable = false)),
			@AttributeOverride(name = "sid", column = @Column(name = "sid", nullable = false)) })
	public TbRoleSecqurityId getId() {
		return this.id;
	}

	public void setId(TbRoleSecqurityId id) {
		this.id = id;
	}

}
