package microservice.online.entity;
// Generated 2017-4-19 18:24:38 by Hibernate Tools 3.2.2.GA

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * TbRoleSecqurityId generated by hbm2java
 */
@Embeddable
public class TbRoleSecqurityId implements java.io.Serializable {

	private static final long serialVersionUID = -3819221153767006956L;
	private int rid;
	private int sid;

	public TbRoleSecqurityId() {
	}

	public TbRoleSecqurityId(int rid, int sid) {
		this.rid = rid;
		this.sid = sid;
	}

	@Column(name = "rid", nullable = false)
	public int getRid() {
		return this.rid;
	}

	public void setRid(int rid) {
		this.rid = rid;
	}

	@Column(name = "sid", nullable = false)
	public int getSid() {
		return this.sid;
	}

	public void setSid(int sid) {
		this.sid = sid;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof TbRoleSecqurityId))
			return false;
		TbRoleSecqurityId castOther = (TbRoleSecqurityId) other;

		return (this.getRid() == castOther.getRid()) && (this.getSid() == castOther.getSid());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getRid();
		result = 37 * result + this.getSid();
		return result;
	}

}
