package microservice.online.entity;
// Generated 2017-4-19 18:24:38 by Hibernate Tools 3.2.2.GA

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * TbUserRole generated by hbm2java
 */
@Entity
@Table(name = "tb_user_role", catalog = "wx_manage")
public class TbUserRole implements java.io.Serializable {

	private TbUserRoleId id;

	public TbUserRole() {
	}

	public TbUserRole(TbUserRoleId id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({ @AttributeOverride(name = "uid", column = @Column(name = "uid", nullable = false)),
			@AttributeOverride(name = "rid", column = @Column(name = "rid", nullable = false)) })
	public TbUserRoleId getId() {
		return this.id;
	}

	public void setId(TbUserRoleId id) {
		this.id = id;
	}

}
